version: '3.5'

services:
  intuit-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: intuit-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - intuit-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - 14306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=9Mc7#GebE4
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

  swagger_ui:
    image: "swaggerapi/swagger-ui"
    container_name: swagger-ui
    volumes:
      - ./storage/api-docs/api-docs.json:/swagger.json
    restart: always
    ports:
      - 9000:8080
    environment:
      - SWAGGER_JSON=/swagger.json
      - BASE_URL=http://localhost:8000/api

networks:
  backend:
    name: backend-network
